---
name: Pull Request Dependency Review
on:
  merge_group:
  pull_request:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
      - uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c  # v4.3.4
        with:
          fail-on-severity: low
          comment-summary-in-pr: on-failure
